name: BriggsRauscherSimulator
channels:
  - defaults
dependencies:
  - python=3.8
  - ipywidgets=7.6.3
  - numpy=1.20.1
  - scipy=1.6.2
  - matplotlib=3.3.4
  - notebook=6.2.0
  - pip
  - pip:
      - ipython==7.21.0  # ipython est nécessaire pour IPython.display
